### ISSUE TITLE
Receiving anothers prompt.

### ISSUE THREAD

**Issue by kel214** [TheOnlyGhostwolf/jermacaption#1]
When generating a caption, I somehow received another person's prompt.
![image_2022-05-16_203727147](https://user-images.githubusercontent.com/45361715/168704016-deab5610-4276-45c8-a4c0-87d1bac4667a.png)

**Comment by pauleks** [comment]
Hey! Does this issue still appear for you?
If yes, then this might be an issue with generating captions. I will look into this.

**Comment by pauleks** [comment]
Heya! Just pushed a fix for this. Let me know if the issue still exists.
